version: '3.1'
services:
    mysql5:
        image: mysql:5.5.60
        restart: always
        hostname: mysql5
        container_name: mysql5
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=mysql
        volumes:
            - /Volumes/data/docker/mysql5:/var/lib/mysql

    adminer:
        image: adminer
        hostname: adminer
        container_name: adminer
        restart: always
        ports:
            - 10080:8080
